/*
 * cytos_xml.cpp:
 *
 * Generates Cytos-compatible XML from an MSystem structure.
 * This allows .mli files to be simulated in the Cytos/Unity engine.
 *
 * Copyright (C) 2024  P-Lingua/M-Lingua Contributors
 * Licensed under GPL-3.0
 */

#include <msystem/cytos_xml.hpp>
#include <sstream>
#include <iomanip>
#include <cmath>

namespace plingua {
namespace msystem {

static std::string xmlEscape(const std::string& s) {
	std::string result;
	for (char c : s) {
		switch (c) {
			case '&': result += "&amp;"; break;
			case '<': result += "&lt;"; break;
			case '>': result += "&gt;"; break;
			case '"': result += "&quot;"; break;
			case '\'': result += "&apos;"; break;
			default: result += c;
		}
	}
	return result;
}

std::string CytosXmlGenerator::generate(const MSystem& sys) {
	std::ostringstream os;
	os << std::fixed << std::setprecision(6);

	os << "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
	os << "<!--\n";
	os << "  Generated by M-Lingua (mlingua) compiler\n";
	os << "  Model: " << xmlEscape(sys.name) << "\n";
	os << "  Type: " << xmlEscape(sys.modelType) << "\n";
	os << "-->\n";
	os << "<root xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
	   << "xsi:noNamespaceSchemaLocation='MSystemXMLSchema.xsd'>\n";

	generateTiling(os, sys);
	generateMSystem(os, sys);

	os << "</root>\n";
	return os.str();
}

void CytosXmlGenerator::generateTiling(std::ostringstream& os, const MSystem& sys) {
	os << "  <tiling>\n";

	// Tiles
	os << "    <tiles>\n";
	for (const auto& tile : sys.tiling.tiles) {
		os << "      <tile name=\"" << xmlEscape(tile.name) << "\">\n";
		os << "        <polygon>\n";
		os << "          <sides value=\"" << tile.sides << "\"/>\n";
		os << "          <radius value=\"" << tile.radius << "\"/>\n";
		os << "        </polygon>\n";

		// Positions
		if (!tile.positions.empty()) {
			os << "        <positions>\n";
			for (const auto& pos : tile.positions) {
				if (pos.name.substr(0, 1) == "v") continue; // vertex positions are auto-generated
				os << "          <position name=\"" << xmlEscape(pos.name) << "\">\n";
				os << "            <posX value=\"" << pos.position.x << "\"/>\n";
				os << "            <posY value=\"" << pos.position.y << "\"/>\n";
				os << "          </position>\n";
			}
			os << "        </positions>\n";
		}

		// Connecting angle
		os << "        <connectingAngle value=\""
		   << (tile.connectingAngle * 180.0 / M_PI) << "\"/>\n";

		// Connectors
		os << "        <connectors>\n";
		for (const auto& conn : tile.connectors) {
			os << "          <connector name=\"" << xmlEscape(conn.name) << "\">\n";
			os << "            <positions>\n";
			for (const auto& vn : conn.vertexNames) {
				os << "              <position name=\"" << xmlEscape(vn) << "\"/>\n";
			}
			os << "            </positions>\n";
			os << "            <glue name=\"" << xmlEscape(conn.glueName) << "\"/>\n";
			if (conn.angles.phi1 != 0) {
				os << "            <angle value=\""
				   << (conn.angles.phi1 * 180.0 / M_PI) << "\" unit=\"deg\"/>\n";
			}
			os << "          </connector>\n";
		}
		os << "        </connectors>\n";

		if (!tile.surfaceGlue.empty()) {
			os << "        <surfaceGlue name=\"" << xmlEscape(tile.surfaceGlue) << "\"/>\n";
		}
		if (!tile.color.name.empty()) {
			os << "        <color name=\"" << xmlEscape(tile.color.name)
			   << "\" alpha=\"" << tile.color.alpha << "\"/>\n";
		}
		os << "      </tile>\n";
	}
	os << "    </tiles>\n";

	// Glues
	os << "    <glues>\n";
	for (const auto& g : sys.tiling.glues) {
		os << "      <glue name=\"" << xmlEscape(g.name) << "\"/>\n";
	}
	os << "    </glues>\n";

	// Glue relations
	os << "    <glueRelations>\n";
	for (const auto& gr : sys.tiling.glueRelations) {
		os << "      <glueTuple glue1=\"" << xmlEscape(gr.glue1)
		   << "\" glue2=\"" << xmlEscape(gr.glue2) << "\"/>\n";
	}
	os << "    </glueRelations>\n";

	// Initial objects (seed tiles)
	os << "    <initialObjects>\n";
	for (const auto& seed : sys.tiling.seedTiles) {
		os << "      <initialObject name=\"" << xmlEscape(seed.tileName) << "\">\n";
		os << "        <posX value=\"" << seed.position.x << "\"/>\n";
		os << "        <posY value=\"" << seed.position.y << "\"/>\n";
		os << "        <posZ value=\"" << seed.position.z << "\"/>\n";
		os << "        <angleX value=\"" << seed.rotation.x << "\"/>\n";
		os << "        <angleY value=\"" << seed.rotation.y << "\"/>\n";
		os << "        <angleZ value=\"" << seed.rotation.z << "\"/>\n";
		os << "      </initialObject>\n";
	}
	os << "    </initialObjects>\n";

	os << "    <glueRadius value=\"" << sys.tiling.glueRadius << "\"/>\n";
	os << "    <randomMovement value=\"" << sys.tiling.randomMovement << "\"/>\n";

	os << "  </tiling>\n";
}

void CytosXmlGenerator::generateMSystem(std::ostringstream& os, const MSystem& sys) {
	os << "  <Msystem>\n";

	// Floating objects
	os << "    <floatingObjects>\n";
	for (const auto& fo : sys.floatingObjects) {
		os << "      <floatingObject name=\"" << xmlEscape(fo.name) << "\">\n";
		os << "        <shape value=\"" << xmlEscape(fo.shape) << "\"/>\n";
		os << "        <size value=\"" << fo.radius << "\"/>\n";
		os << "        <mobility value=\"" << fo.mobility << "\"/>\n";
		os << "        <concentration value=\"" << fo.concentration << "\"/>\n";
		os << "      </floatingObject>\n";
	}
	os << "    </floatingObjects>\n";

	// Proteins (protions)
	os << "    <proteins>\n";
	for (const auto& p : sys.protions) {
		os << "      <protein name=\"" << xmlEscape(p.name) << "\"/>\n";
	}
	os << "    </proteins>\n";

	// Proteins on tiles
	os << "    <proteinsOnTiles>\n";
	for (const auto& pot : sys.protionsOnTiles) {
		os << "      <proteinOnTile protein=\"" << xmlEscape(pot.protionName)
		   << "\" tile=\"" << xmlEscape(pot.tileName) << "\">\n";
		os << "        <posX value=\"" << pot.position.x << "\"/>\n";
		os << "        <posY value=\"" << pot.position.y << "\"/>\n";
		os << "      </proteinOnTile>\n";
	}
	os << "    </proteinsOnTiles>\n";

	// Rules
	os << "    <evoRulesWithPriority>\n";
	for (const auto& rule : sys.rules) {
		generateRule(os, rule);
	}
	os << "    </evoRulesWithPriority>\n";

	// Signal objects
	os << "    <signalObjects>\n";
	for (const auto& sr : sys.signalReleases) {
		os << "      <signal glue1=\"" << xmlEscape(sr.glue1)
		   << "\" glue2=\"" << xmlEscape(sr.glue2) << "\">\n";
		for (const auto& pair : sr.released) {
			for (size_t i = 0; i < pair.second.raw(); i++) {
				os << "        <object name=\"" << xmlEscape(pair.first.str()) << "\"/>\n";
			}
		}
		os << "      </signal>\n";
	}
	os << "    </signalObjects>\n";

	os << "  </Msystem>\n";
}

void CytosXmlGenerator::generateRule(std::ostringstream& os, const MRule& rule) {
	std::string typeStr;
	switch (rule.type) {
		case MRuleType::CREATION: typeStr = "Create"; break;
		case MRuleType::DESTRUCTION: typeStr = "Destroy"; break;
		case MRuleType::DIVISION: typeStr = "Divide"; break;
		default: typeStr = "Metabolic"; break;
	}

	os << "      <evoRule type=\"" << typeStr << "\"";
	if (rule.priority != 0) {
		os << " priority=\"" << rule.priority << "\"";
	}
	os << ">\n";

	// Left side
	std::string leftStr;
	if (rule.type == MRuleType::DIVISION) {
		leftStr = rule.glue1;
		for (const auto& pair : rule.leftObjects) {
			leftStr += "," + pair.first.str();
			if (pair.second.raw() > 1) {
				leftStr += "*" + std::to_string(pair.second.raw());
			}
		}
		leftStr += "," + rule.glue2;
	} else {
		for (const auto& pair : rule.leftObjects) {
			if (!leftStr.empty()) leftStr += ",";
			leftStr += pair.first.str();
			if (pair.second.raw() > 1) {
				leftStr += "*" + std::to_string(pair.second.raw());
			}
		}
	}

	// Right side
	std::string rightStr;
	if (rule.type == MRuleType::CREATION) {
		rightStr = rule.tileName;
	} else if (rule.type == MRuleType::DIVISION) {
		rightStr = rule.glue1 + "," + rule.glue2;
	} else {
		for (const auto& pair : rule.rightObjects) {
			if (!rightStr.empty()) rightStr += ",";
			rightStr += pair.first.str();
			if (pair.second.raw() > 1) {
				rightStr += "*" + std::to_string(pair.second.raw());
			}
		}
	}

	os << "        <leftside value=\"" << xmlEscape(leftStr) << "\"/>\n";
	os << "        <rightside value=\"" << xmlEscape(rightStr) << "\"/>\n";
	os << "      </evoRule>\n";
}

} // namespace msystem
} // namespace plingua
